site_name: mkdocs-jupyterlite
theme:
  name: material
  features:
    - navigation.instant
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: repl
          class: iframe
          format: !!python/name:mkdocs_jupyterlite.superfences.repl_formater
          validator: !!python/name:mkdocs_jupyterlite.superfences.repl_validator
    


plugins:
  - search
  - jupyterlite-plugin:
      environments:
        my_env:
          build: 1
          env_file: lite_envs/with_numpy/env.yaml
          notebook_dir: notebooks
          notebook_pattern: "*.py"
          notebook_doc_path: "examples/notebooks"
          kernel_mapping:
            py: xpython
          mounts:
            - host: lite_envs/with_numpy/mounts/some_mount
              target: "/some/target/dir"
        themes_env:
          build: 1
          env_file: lite_envs/themes/env.yaml
          notebook_dir: notebooks
          notebook_pattern: "NOT*.py"
          notebook_doc_path: "examples/notebooks"
          kernel_mapping:
            py: xpython
          mounts:
            - host: lite_envs/themes/mounts/some_mount
              target: "/some/target/dir"
          







